image: registry.labs.nic.cz/turris/turris-updater-lists

stages:
  - build
  - check

.configure:
  before_script:
    - ./configure -f /feeds.conf


## Build stage ###################################################################
build:
  stage: build
  extends: .configure
  script:
    - make

## Check stage ###################################################################
lint:
  stage: check
  extends: .configure
  script:
    - make lint

test:
  stage: check
  extends: .configure
  script:
    - make -k test
