stages:
  - docker
  - build
  - check

image: "$CI_REGISTRY_IMAGE"

## Docker stage ##################################################################
docker:
  stage: docker
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker
  services:
    - $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:dind
  tags:
    - dind
    - privileged
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE" --tag "$CI_REGISTRY_IMAGE" --file .gitlab-ci/Dockerfile .gitlab-ci
    - docker push "$CI_REGISTRY_IMAGE"

## Build stage ###################################################################
build:
  stage: build
  needs:
    - job: docker
      artifacts: false
  script:
    - ./configure -f /feeds.conf
    - make
  artifacts:
    paths:
      - '.config.mk'
      - 'output/'

## Check stage ###################################################################
lint:
  stage: check
  needs: [build]
  script:
    - make lint

test:
  stage: check
  needs: [build]
  script:
    - make -k test
